import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import 'mapbox-gl/dist/mapbox-gl.css';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} bg-black antialiased h-[100dvh] w-screen max-w-md overflow-hidden flex justify-center items-center`}
      >
        {children}
      </body>
    </html>
  );
}
