import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import 'mapbox-gl/dist/mapbox-gl.css';
import { Providers } from './providers';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} bg-background text-foreground antialiased h-[100dvh] w-screen max-w-md overflow-hidden flex justify-center items-center`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
